In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import numpy as np
import matplotlib.pyplot as plt
import torchvision.transforms as transforms

In [2]:
# hyper-parameter
num_epochs = 4
batch_size = 4
learning_rate = 0.001

In [3]:
# datasets as PILImage images of range [0, 1].
# we transform them to Tensor pf normalized range [-1, 1]
transform = transforms.Compose(
                                [transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])


In [4]:
train_datasets = torchvision.datasets.CIFAR10(root="./datacifar", train=True,
                                             download=False, transform=transform)

In [5]:
test_datasets = torchvision.datasets.CIFAR10(root="./datacifar", train=False,
                                            download=False, transform=transform)

In [6]:
train_loader = torch.utils.data.DataLoader(train_datasets, batch_size=batch_size,
                                                shuffle=True)
test_loader = torch.utils.data.DataLoader(test_datasets, batch_size=batch_size, 
                                               shuffle=False)

In [7]:
dataiter = iter(train_loader)
data = next(dataiter)
n_samples, n_labels = data
n_samples.size(), n_labels.size()

(torch.Size([4, 3, 32, 32]), torch.Size([4]))

In [8]:
#n_samples

In [9]:
for i, (images, labels) in enumerate(train_loader):
    
    model = nn.Conv2d(3, 6, 5)
    out = model(images)
print(out.shape)

torch.Size([4, 6, 28, 28])


In [10]:
print(out.shape)

torch.Size([4, 6, 28, 28])


In [11]:
model = nn.MaxPool2d(2, 2)
out = model(out)

In [12]:
out.shape

torch.Size([4, 6, 14, 14])

In [13]:
model = nn.Conv2d(6, 16, 5)
out = model(out)

In [14]:
out.shape

torch.Size([4, 16, 10, 10])

In [15]:
import torch
#help(torch.nn.Conv2d)

In [16]:
classes = ("plane", "car", "bird", "cat", "deer", "dog",
          "frog", "horse", "ship", "truck")

In [17]:
class ConvNet(nn.Module):
    def __init__(self, ):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16*5*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        
        return x
    
model = ConvNet()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [18]:
model = ConvNet()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [19]:
n_total_steps = len(train_loader)
for epochs in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
    
        outputs = model(images)
        loss = criterion(outputs, labels)


        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        
        if (i+1) % 100 == 0:
            print(f"epoch {epochs + 1} / {num_epochs}, step {i+1}/{n_total_steps}, loss = {loss.item():.4f}")
            
print("Finish Training")
    

epoch 1 / 4, step 100/12500, loss = 2.3335
epoch 1 / 4, step 200/12500, loss = 2.3140
epoch 1 / 4, step 300/12500, loss = 2.2570
epoch 1 / 4, step 400/12500, loss = 2.3256
epoch 1 / 4, step 500/12500, loss = 2.2937
epoch 1 / 4, step 600/12500, loss = 2.2711
epoch 1 / 4, step 700/12500, loss = 2.2739
epoch 1 / 4, step 800/12500, loss = 2.2723
epoch 1 / 4, step 900/12500, loss = 2.3235
epoch 1 / 4, step 1000/12500, loss = 2.3695
epoch 1 / 4, step 1100/12500, loss = 2.2850
epoch 1 / 4, step 1200/12500, loss = 2.3099
epoch 1 / 4, step 1300/12500, loss = 2.2945
epoch 1 / 4, step 1400/12500, loss = 2.3456
epoch 1 / 4, step 1500/12500, loss = 2.2625
epoch 1 / 4, step 1600/12500, loss = 2.3101
epoch 1 / 4, step 1700/12500, loss = 2.3065
epoch 1 / 4, step 1800/12500, loss = 2.3162
epoch 1 / 4, step 1900/12500, loss = 2.3380
epoch 1 / 4, step 2000/12500, loss = 2.2747
epoch 1 / 4, step 2100/12500, loss = 2.2771
epoch 1 / 4, step 2200/12500, loss = 2.2603
epoch 1 / 4, step 2300/12500, loss = 2.30

In [20]:
import torch

x = torch.tensor([[1], [4], [6], [8], [0]])
y = torch.tensor([[5, 6, 6, 9, 0]])

#(x == y).sum()
_, pred = torch.max(y, 1)


In [35]:
with torch.no_grad():
    n_correct = 0
    n_samples = 0
    n_class_correct = [0 for i in range(10)]
    n_class_samples = [0 for i in range(10)]
    for images, labels in test_loader:
        
        
        outputs = model(images)
        print(outputs)
        print(outputs.shape)
        
        
        _, predicted = torch.max(outputs, 1)
        print(predicted);print(_);print(labels)
        n_samples += labels.shape[0]
        n_correct += (predicted == labels).sum().item()
        

tensor([[-1.0306, -0.4274,  0.0906,  2.7789, -0.6217,  1.6078,  1.1590, -1.2656,
          0.3006, -0.2183],
        [ 4.2612,  5.8656, -1.6336, -2.3840, -2.0169, -4.1463, -3.5525, -2.7102,
          5.8166,  4.5959],
        [ 2.3393,  4.0245, -1.0838, -1.0640, -1.9591, -2.4140, -2.7008, -1.4731,
          3.3606,  3.4374],
        [ 3.5786,  2.9710, -0.1152, -1.4364, -0.2453, -2.7958, -2.4233, -1.7557,
          3.8009,  1.3908]])
torch.Size([4, 10])
tensor([3, 1, 1, 8])
tensor([2.7789, 5.8656, 4.0245, 3.8009])
tensor([3, 8, 8, 0])
tensor([[-1.2890, -2.0056,  1.6446,  2.2785,  2.4244,  1.6887,  3.1792,  0.3218,
         -2.5054, -2.2007],
        [-0.1201,  0.2670,  0.1090,  0.4559,  1.0766, -0.3771,  2.8473, -0.1744,
         -0.8335,  0.0700],
        [ 1.2587,  2.4947, -0.8472,  1.4217, -0.4150,  1.4859, -1.3628,  1.1202,
          0.9190,  0.5926],
        [-1.0458, -2.5703,  1.5711,  1.7062,  2.4199,  1.0101,  2.7765,  0.3097,
         -2.3749, -1.6341]])
torch.Size([4, 10])
ten

In [21]:
with torch.no_grad():
    n_correct = 0
    n_samples = 0
    n_class_correct = [0 for i in range(10)]
    n_class_samples = [0 for i in range(10)]
    for images, labels in test_loader:
        
        
        outputs = model(images)
        
        
        _, predicted = torch.max(outputs, 1)
        n_samples += labels.shape[0]
        n_correct += (predicted == labels).sum().item()
        
        for i in range(batch_size):
            label = labels[i]
            pred = predicted[i]
            if (label == pred):
                n_class_correct[label] += 1
            n_class_samples[label] += 1
        
    
    acc = 100.0 * (n_correct / n_samples) 
    print(f"accuracy = {acc}")
    
    for i in range(10):
        acc = 100.0 * n_class_correct[i] / n_class_samples[i]
        print(f"Accuracy of {classes[i]}: {acc} %")

accuracy = 48.699999999999996
Accuracy of plane: 60.2 %
Accuracy of car: 73.3 %
Accuracy of bird: 11.2 %
Accuracy of cat: 35.1 %
Accuracy of deer: 37.2 %
Accuracy of dog: 41.9 %
Accuracy of frog: 68.5 %
Accuracy of horse: 58.8 %
Accuracy of ship: 53.4 %
Accuracy of truck: 47.4 %


In [31]:
outputs[0]



tensor([-1.2304, -2.2750,  0.8390,  2.4796,  2.1925,  1.7468,  3.2282,  1.0494,
        -2.5364, -2.2414])

In [22]:
import numpy as np

In [23]:
an_array = np.array([[[1, 2, 3, 6, 4], [2, 3, 6, 8, 7], [5, 7, 9, 5, 3], [0, 1, 1, 0, 2]]])

In [24]:
an_array

array([[[1, 2, 3, 6, 4],
        [2, 3, 6, 8, 7],
        [5, 7, 9, 5, 3],
        [0, 1, 1, 0, 2]]])

In [25]:
an_array.shape

(1, 4, 5)

In [26]:
an_array.size

20

In [27]:
#an_array = an_array.reshape(0, 1, 20)

In [28]:
an_array.shape

(1, 4, 5)